name: Linter

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    linter:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    extensions: pdo_sqlite, pdo_mysql, pdo_pgsql
                    coverage: none

            -   run: composer install --no-progress
            -   run: vendor/bin/parallel-lint src tests -e php,phpt
